name: Auto PR on push

on:
  push:
    branches-ignore:
      - main                
      - 'dependabot/**'
      - 'renovate/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  open-or-update-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure PR exists (create if missing)
        uses: actions/github-script@v7
        with:
          # ⚠️ Utilise le PAT stocké en secret pour éviter le 403
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            const owner  = context.repo.owner;
            const repo   = context.repo.repo;

            // Sécurité : on ne crée pas de PR depuis main
            if (branch === 'main') {
              core.info('Skip on main');
              return;
            }

            // Récupère le dernier commit pour le titre/description
            const { data: commit } = await github.rest.repos.getCommit({
              owner, repo, ref: context.sha
            });
            const headMsg = (commit.commit.message || '').split('\n')[0].trim();
            const isDraft = /(^|\s)WIP(\s|:|$)/i.test(commit.commit.message || '');

            // Cherche une PR ouverte de branch -> main
            const { data: prs } = await github.rest.pulls.list({
              owner, repo, state: 'open', head: `${owner}:${branch}`, base: 'main'
            });

            if (prs.length > 0) {
              core.info(`PR déjà ouverte: #${prs[0].number} ${prs[0].html_url}`);
              return;
            }

            const title = `${branch} – ${headMsg || 'Mise à jour'}`;
            const body  = [
              `PR créée automatiquement suite à un push sur \`${branch}\`.`,
              '',
              `Dernier commit: ${context.sha}`
            ].join('\n');

            const { data: pr } = await github.rest.pulls.create({
              owner, repo,
              title,
              head: branch,
              base: 'main',       // ➜ change en 'develop' si besoin
              body,
              draft: isDraft      // PR en brouillon si le commit contient "WIP"
            });

            core.info(`✅ PR créée: #${pr.number} ${pr.html_url}`);

      # (Optionnel) Ajouter un label automatiquement
      - name: Add "auto-pr" label
        if: ${{ success() }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const branch = context.ref.replace('refs/heads/', '');

            const { data: prs } = await github.rest.pulls.list({
              owner, repo, state: 'open', head: `${owner}:${branch}`, base: 'main'
            });
            if (prs.length === 0) return;

            await github.rest.issues.addLabels({
              owner, repo, issue_number: prs[0].number,
              labels: ['auto-pr']
            });
